### ISSUE TITLE
not P25 ID found Why?

### ISSUE THREAD

**Issue by bg3hbr** [juribeparada/YSF2P25#2]
M: 2018-05-16 15:13:39.367 Received YSF Header: Src: BG3ITR     Dst: *****H54TJ
M: 2018-05-16 15:13:39.367 Not P25 ID found, using default ID: 4603003, DstID: TG 8208
M: 2018-05-16 15:13:41.648 YSF received end of voice transmission, 2.2 seconds

**Comment by juribeparada** [comment]
That happens when your callsign BG3ITR is not in the database DMRIds.dat
